Monitor section
vaibhav-yb/yugabyte-db pull request #4
Opened 2024-07-18 17:17 UTC by siddharth2411

2024-07-18 19:33 UTC, vaibhav-yb requested changes

2024-07-18 19:33 UTC, vaibhav-yb commented on docs/content/preview/explore/change-data-capture/using-logical-replication/monitor.md
> +| ----------------------- | --------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------
```suggestion
| Column name | Data type | Description |
| :----- | :----- | :----- |
```

2024-07-18 19:33 UTC, vaibhav-yb commented on docs/content/preview/explore/change-data-capture/using-logical-replication/monitor.md
> +| ----------- | --------- | ------------------------------- |
```suggestion
| Column name | Data type | Description |
| :----- | :----- | :----- |
```

2024-07-18 19:33 UTC, vaibhav-yb commented on docs/content/preview/explore/change-data-capture/using-logical-replication/monitor.md
> +| tablename   | name      | Name of table                   |
What does the data type `name` mean? Either it would be a `varchar` or `text`- or am I misunderstanding something?

2024-07-18 19:33 UTC, vaibhav-yb commented on docs/content/preview/explore/change-data-capture/using-logical-replication/monitor.md
> +Provides a listing of all replication slots that currently exist on the database cluster, along with their metadata.
```suggestion
Provides a list of all replication slots that currently exist on the database cluster, along with their metadata.
```

2024-07-18 19:33 UTC, vaibhav-yb commented on docs/content/preview/explore/change-data-capture/using-logical-replication/monitor.md
> +| slot\_name              | name      | Name of the replication slot
```suggestion
| slot_name| name | Name of the replication slot |
```

2024-07-18 19:33 UTC, vaibhav-yb commented on docs/content/preview/explore/change-data-capture/using-logical-replication/monitor.md
> +| yb\_restart\_commit\_ht | int8      | A uint64 representation of the commit Hybrid Time corresponding to the restart\_lsn. This can be used by the client (like YB-PG Connector) to perform a consist
```suggestion
| plugin | name | Output plugin name (Always `yboutput`) |
| slot_type | text | Always logical |
| datoid | oid | The OID of the database this slot is associated with. |
| database | text | The name of the database this slot is associated with. |
| temporary | boolean | True if this is a temporary replication slot. Temporary slots are automatically dropped on error or when the session has finished. |
| active | boolean | True if this slot is currently actively being used. In YSQL, an "active" replication slot means a slot which has been consumed at least once in a certain timeframe. We will define this timeframe via a GFlag `ysql_replication_slot_activity_threshold` with a default value of 5 minutes. |
| active_pid | integer | The process ID of the session using this slot if the slot is currently actively being used. `NULL` if inactive. |
| xmin | xid | The oldest transaction that this slot needs the database to retain. VACUUM cannot remove tuples deleted by any later transaction. |
| catalog_xmin | xid | The oldest transaction affecting the system catalogs that this slot needs the database to retain. VACUUM cannot remove catalog tuples deleted by any later transaction. |
| restart_lsn | pg_lsn | The address (LSN) of oldest WAL which still might be required by the consumer of this slot and thus won't be automatically removed during checkpoints. NULL if the LSN of this slot has never been reserved. |
| confirmed_flush_lsn | pg_lsn | The address (LSN) up to which the logical slot's consumer has confirmed receiving data. Data older than this is not available anymore. `NULL` for physical slots. |
| yb_stream_id | text | UUID of the CDC stream |
| yb_restart_commit_ht | int8 | A uint64 representation of the commit Hybrid Time corresponding to the restart_lsn. This can be used by the client (like YugabyteDB connector) to perform a consistent snapshot (as of the consistent_point) in the case when a replication slot already exists. |
```

2024-07-18 19:33 UTC, vaibhav-yb commented on docs/content/preview/explore/change-data-capture/using-logical-replication/monitor.md
> +### pg\_publication
```suggestion
### pg_publication
```

2024-07-18 19:33 UTC, vaibhav-yb commented on docs/content/preview/explore/change-data-capture/using-logical-replication/monitor.md
> +| prrelid     | oid       | OID of the relation. References pg\_class.oid          |
```suggestion
| Column name | Data type | Description |
| :----- | :----- | :----- |
| oid | oid | Row identifier |
| prpubid | oid | OID of the publication. References pg_publication.oid |
| prrelid | oid | OID of the relation. References pg_class.oid |
```

2024-07-18 19:33 UTC, vaibhav-yb commented on docs/content/preview/explore/change-data-capture/using-logical-replication/monitor.md
> +| pubtruncate  | bool      | If true, TRUNCATE operations are replicated for tables in the publication.                         |
```suggestion
| Column name  | Data type | Description |
| :----- | :----- | :----- |
| oid | oid | Row identifier |
| pubname | name | Name of the publication |
| pubowner | oid | OID of the owner. |
| puballtables | bool | If true, this publication includes all tables in the database including those added in the future. |
| pubinsert | bool | If true, INSERT operations are replicated for tables in the publication. |
| pubupdate | bool | If true, UPDATE operations are replicated for tables in the publication. |
| pubdelete | bool | If true, DELETE operations are replicated for tables in the publication. |
| pubtruncate | bool | If true, TRUNCATE operations are replicated for tables in the publication. |
```

2024-07-18 19:33 UTC, vaibhav-yb commented on docs/content/preview/explore/change-data-capture/using-logical-replication/monitor.md
> +| tablename   | name      | Name of table                   |
```suggestion
| pubname | name | Name of publication |
| schemaname | name | Name of schema containing table |
| tablename | name | Name of table |
```

2024-07-22 13:15 UTC, siddharth2411 commented on docs/content/preview/explore/change-data-capture/using-logical-replication/monitor.md
> +| tablename   | name      | Name of table                   |
Even [Postgres official docs](https://www.postgresql.org/docs/11/view-pg-publication-tables.html) use 'name'. So, would prefer to continue using the same.

2024-07-22 16:30 UTC, merged